// Cartoon illustrations generated by scripts/generate-art.mjs (npm run art).

const URLS = import.meta.glob('../assets/art/*.svg', { eager: true, query: '?url', import: 'default' }) as Record<string, string>

const BY_NAME: Record<string, string> = Object.fromEntries(
  Object.entries(URLS).map(([path, url]) => [path.split('/').pop()!.replace('.svg', ''), url]),
)

export function artUrl(name: string): string {
  const url = BY_NAME[name]
  if (!url) throw new Error(`Unknown art "${name}"`)
  return url
}

export function Art({ name, className = 'size-10', alt = '' }: { name: string; className?: string; alt?: string }) {
  return <img src={artUrl(name)} alt={alt} className={`select-none ${className}`} draggable={false} />
}

/** "Pluto & Mars" -> ['pluto', 'mars'] */
export function rulerArt(ruler: string): string[] {
  return ruler.split(' & ').map((r) => r.trim().toLowerCase())
}
